### ISSUE TITLE
NexusBridge.js

### ISSUE THREAD

**Issue by alokpal570** [ideaportriga/nexus-bridge#197]
# Bug report

NexusBridge. js  file is not available in archive file as well as in code.

**Comment by OllegK** [comment]
Thank you for reporting that, this is because we changed the way how to publish the NexusBridge. Now you can download the archive that contains the standalone compiled version using the link https://registry.npmjs.org/@ideaportriga/nexus-bridge/-/nexus-bridge-2.3.12.tgz

**Comment by OllegK** [comment]
Updated https://github.com/ideaportriga/nexus-bridge/wiki/Setup-Nexus-Bridge
