### ISSUE TITLE
Move CreatePopupNB to nexus-factory

### ISSUE THREAD

**Issue by esneko** [ideaportriga/nexus-bridge#72]
## Feature Request

**Move CreatePopupNB to nexus-factory**

Proposed implementation:
```
import { memoizeOnce, NexusFactory } from '@ideaportriga/nexus-factory'

const pickApplet = memoizeOnce(appletName, fieldName)
```

**Comment by esneko** [comment]
`NexsusPopup` API still needs additional changes.
Do not close with #75

**Comment by OllegK** [comment]
I think we have #73 for additional changes
