### ISSUE TITLE
Use conversion settings in factory or provide a way to send the options objects

### ISSUE THREAD

**Issue by OllegK** [ideaportriga/nexus-bridge#73]
## Feature Request
This feature is useful for multilingual deployments
Give an option to populate:
* returnRawNumbers
* returnRawCurrencies

**Comment by OllegK** [comment]
In addition, maybe the "conversion" settings should be shared among all instances of NB

**Comment by OllegK** [comment]
This repository is for Nexus Bridge only.

**Comment by esneko** [comment]
In case we do not support `nexus-factory` publicly, we have to refactor React example without `nexus-factory` and move `nexus-factory` to private repo.
