### ISSUE TITLE
Replace N19/n19 with Nexus/nexus in code and filenames

### ISSUE THREAD

**Issue by esneko** [ideaportriga/nexus-bridge#80]
## Feature Request

**Replace N19/n19 with Nexus/nexus in code and filenames**

Let's create the name conventions for Nexus, e.g. call it NexusBridge and all prototypes start with Nexus* as well:
```
export default class NexusBridge extends NexusBaseApplet
```

Next step the auto-generated typings from `nexus-bridge` can replace the built-in typings in `nexus-factory`:
```
export interface NexusBridge {
    [key: string]: any
}
```

**Comment by OllegK** [comment]
In addition, remove staticLOV, lovs, readOnly controls' attributes.
